#https://github.com/nanoninja/docker-nginx-php-mysql
version: '2'
services:
    web:
        container_name: jira-sdk-js-web.hipay-pos-platform.com
        image: nginx:latest
        ports:
            - "8501:80"
#            - "3000:443"
#            - "3000:443"
        restart: always
        volumes:
#            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
#            - "./etc/ssl:/etc/ssl"
            - "./:/web"
        depends_on:
            - "php"
#            - "mysqldb"
    php:
        container_name: jira-sdk-js-php.hipay-pos-platform.com
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - .:/web
    composer:
        container_name: jira-sdk-js-composer.hipay-pos-platform.com
        image: composer/composer
        volumes:
            - .:/app
        command: install
    npm:
        container_name: jira-sdk-js-npm.hipay-pos-platform.com
        image: node
        volumes:
            - .:/data
        working_dir: /data
        entrypoint: ['npm', '--no-bin-link']
        command: install

#    myadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        ports:
#            - "8080:80"
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=mysql
#        restart: always
#        depends_on:
#            - "mysqldb"
#    mysqldb:
#        image: mysql
#        container_name: mysql
#        restart: always
#        environment:
#            - MYSQL_DATABASE=test
#            - MYSQL_ROOT_PASSWORD=root
#            - MYSQL_USER=dev
#            - MYSQL_PASSWORD=dev
#        ports:
#            - 3306:3306
#        volumes:
#            - ./data/db/mysql:/var/lib/mysql

